name: odbc_fast
version: 0.1.0
description: Enterprise-grade ODBC data platform for Dart

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  windows:
  linux:
  macos:

dependencies:
  ffi: ^2.1.5
  result_dart: ^2.0.0
  logging: ^1.3.0
  dotenv: ^4.2.0

dev_dependencies:
  ffigen: ^20.1.1
  test: ^1.24.0
  benchmark_harness: ^2.2.2
  lints: ^6.0.0
  very_good_analysis: ^10.0.0

topics:
  - db
  - database
  - odbc
  - sqlserver
  - oracle
  - postgresql
  - mysql
  - sqlite
  - mariadb
  - mssql
  - sybase
  - db2
  - informix

